apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-app
    newName: jhjun07/jifelog-app
    newTag: prod-74f7ccf606b0fec1c3309fb53c77f38fd84293fc

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
