apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jifelog-app-ingress
spec:
  ingressClassName: public
  rules:
    - host: jifelog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jifelog-app
                port:
                  number: 80
    - host: www.jifelog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jifelog-app
                port:
                  number: 80
