apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-app
    newName: jhjun07/jifelog-app
    newTag: dev-2105ed101d6f24f0544d15bdb8aa48f39d006b03

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
