apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-app
    newName: jhjun07/jifelog-app
    newTag: dev-750f6b56eb4bfc1a8651fb38b13ae92ae6b37c72

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
